import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MiniDrawer from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  // 追加のプロパティがあればここに追加
  children: React.ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="ja">
      <body>
        <MiniDrawer>
        </MiniDrawer>
      </body>
    </html>
  )
}
